# Generated by Django 5.0.4 on 2024-05-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contents',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
