# Generated by Django 5.0.4 on 2024-05-02 20:23

import django.core.validators
import django.db.models.deletion
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_contents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(help_text='Required.', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='contents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='project-images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Required. Your project name should consist of only letters, numbers, hypens, underscores, and spaces. It should not be named the same as any of your other projects.', max_length=80, validators=[django.core.validators.RegexValidator(message='Please enter a valid project name. This value may contain only letters, numbers, hyphens, underscores, and spaces. It must additionally contain at least one non-space character.', regex='^[\\w\\s-]$')], verbose_name='Project name'),
        ),
    ]
