# Generated by Django 5.0.4 on 2024-05-02 20:52

import django.core.validators
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to=projects.models.get_image_file_name),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Required. Your project name should consist of only letters, numbers, hypens, underscores, and spaces. It should not be named the same as any of your other projects.', max_length=80, validators=[django.core.validators.RegexValidator(message='Please enter a valid project name. This value may contain only letters, numbers, hyphens, underscores, and spaces. It must additionally contain at least one non-space character.', regex='^[\\w\\s-]+$')], verbose_name='project name'),
        ),
    ]
