# Generated by Django 5.0.4 on 2024-05-16 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_project_completed_project_is_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=80)),
                ('body', models.TextField(blank=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='projects.project', verbose_name='parent project')),
            ],
            options={
                'indexes': [models.Index(fields=['parent'], name='projects_pr_parent__87622a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='projectsection',
            constraint=models.CheckConstraint(check=models.Q(('heading__isnull', False), ('body__isnull', False), _connector='OR'), name='not_both_null'),
        ),
    ]
