# Generated by Django 5.0.4 on 2024-05-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectsection_projectsection_not_both_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contents',
        ),
    ]
